# SaltStack Packer Lint Circle CI
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install packer 
          command: |
            sudo wget https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip && sudo unzip packer_1.3.3_linux_amd64.zip -d /usr/bin
      - run:
          name: lint packer code
          command: |
            packer validate -var-file=AWS/ubuntu/ubuntu-1804-us-west-2.json AWS/ubuntu/ubuntu.json
            
