# SaltStack Packer Lint Circle CI
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install packer 
          command: |
            sudo wget https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip && sudo unzip packer_1.3.3_linux_amd64.zip -d /usr/bin
      - run:
          name: lint centos
          command: |
            sudo make build OS=centos OS_REV=6 && sudo make build OS=centos OS_REV=7
      - run:
          name: lint debian
          command: |
            sudo make build OS=debian OS_REV=8 && sudo make build OS=debian OS_REV=9
      - run:
          name: lint fedora
          command: |
            sudo make build OS=fedora OS_REV=28 && sudo make build OS=fedora OS_REV=29
      - run:
          name: lint suse
          command: |
            sudo make build OS=opensuse OS_REV=42.3
      - run:
          name: lint ubuntu
          command: |
            sudo make build OS=ubuntu OS_REV=1404 && sudo make build OS=ubuntu OS_REV=1604 && sudo make build OS=ubuntu OS_REV=1804
